### ISSUE TITLE
Random logic sig address

### ISSUE THREAD

**Issue by gidonkatten** [scale-it/algo-builder#299]
In `runtime` `getLogicSig`, the address should be the compiled TEAL program and not a randomly generated address. Use case: have hardcoded escrow account address into contract.

**Comment by robert-zaremba** [comment]
I guess your use case is to provide an address to a smart-contract template - customize a smart-contract using an external variable.

We created a small Python module for that: [algobpy](https://github.com/scale-it/algo-builder/tree/master/examples/algobpy). So the best way is to:
* copy that directory and place it in your project
* see example how to use it in a [smart-contract](https://github.com/scale-it/algo-builder/blob/master/examples/crowdfunding/assets/crowdFundEscrow.py#L47) and in a [script](https://github.com/scale-it/algo-builder/blob/master/examples/crowdfunding/scripts/createApp.js#L59).

We have a user documentation about the smart contract [External Parameters Support](https://github.com/scale-it/algo-builder/blob/master/docs/guide/py-teal.md#external-parameters-support).

Let me know if this solves your problem.

**Comment by gidonkatten** [comment]
Yes I have done that and it solves the problem, thanks!
