### ISSUE TITLE
Issue with Runtime - sending integer App Arguments

### ISSUE THREAD

**Issue by moon-gazer** [scale-it/algo-builder#308]
We are observing an error which seems to be stemming from algob runtime. It is not observed when goal is used directly. Below is the description: 

Consider the following PyTEAL contract:

```
from pyteal import *

def approval_program():

on_create = Seq([
    App.globalPut(Concat(Txn.application_args[0], Bytes("test_")), Btoi(Txn.application_args[0])),
    Int(1),
])

on_closeout = Int(1)

on_opt_in = Int(1)

on_test = App.globalGet(Concat(Itob(Txn.xfer_asset()), Bytes("test_")))

program = Cond(
    [Txn.application_id() == Int(0), on_create],
    [Txn.on_completion() == OnComplete.CloseOut, on_closeout],
    [Txn.on_completion() == OnComplete.OptIn, on_opt_in],
    [Txn.type_enum() == TxnType.AssetTransfer, on_test],
)    
return program
```

Steps:
1. create the asset
2. create the app
3. account opts in to app
4. send the asset (throws an error: "type of data is incorrect. Expected object but got bigint at line 325")

This is when we are using the Runtime in algob to execute the transactions.
The app args array for the creation call is: `[`int:${assetID}`]`
The creation call is:
```
{
    type: types.TransactionType.CallNoOpSSC,
    sign: types.SignType.SecretKey,
    fromAccountAddr: fromAccount,
    appId: applicationId,
    appArgs: [`int:${assetID}`],
    payFlags: { totalFee: systemFee }
  }
```
The asset transfer call to call on_test is:
```
{
    type: types.TransactionType.TransferAsset,
    sign: types.SignType.SecretKey,
    fromAccountAddr: fromAccount ,
    toAccountAddr: toAccount,
    amount: amount,
    assetID: assetID,
    payFlags: { totalFee: systemFee }
};
```

We get the below error from runtime:  "type of data is incorrect. Expected object but got bigint at line 325"
Could you please help with the same?
The error is not obtained when steps 1 to 4 are done using goal.

**Comment by ratik21** [comment]
Hi @moon-gazer. I am not sure if i follow the transaction parameters you shared. Could you please verify them? 
> The creation call is:
```
{
    type: types.TransactionType.CallNoOpSSC,
    sign: types.SignType.SecretKey,
    fromAccountAddr: fromAccount, // note: key here should be "fromAccount" (not fromAccountAddr)
    appId: applicationId,
    appArgs: [`int:${assetID}`],
    payFlags: { totalFee: systemFee }
  }
```
This is a `NoOp` call to the smart contract (also could you check the code in approval program if you're handling noOp call?). To create/deploy the app, you'll need to use `runtime.addApp(..)`

> The asset transfer call to call on_test is:
```
{
    type: types.TransactionType.TransferAsset,
    sign: types.SignType.SecretKey,
    fromAccountAddr: fromAccount , // note: key here should be "fromAccount" (not fromAccountAddr)
    toAccountAddr: toAccount,
    amount: amount,
    assetID: assetID,
    payFlags: { totalFee: systemFee }
};
```
How is the call to stateful smart contract involved here? Or is it in a transaction group? Could you please clarify?

**Comment by ratik21** [comment]
> Steps:
> 
>     1. create the asset
> 
>     2. create the app
> 
>     3. account opts in to app
> 
>     4. send the asset (throws an error: "type of data is incorrect. Expected object but got bigint at line 325")

This is how i constructed the test till step 3:
```js
const master = new AccountStore(1000e6);
const alice = new AccountStore(minBalance, { addr: aliceAddr, sk: new Uint8Array(0) });
const bob = new AccountStore(minBalance, { addr: bobAddr, sk: new Uint8Array(0) });
const runtime = new Runtime([master, alice, bob]);

creationFlags = {
  sender: alice.account,
  localInts: 5,
  localBytes: 5,
  globalInts: 5,
  globalBytes: 5
};

// create asset
assetId = runtime.addAsset('gold', { creator: { ...alice.account, name: 'alice' } });

// create app
applicationId = runtime.addApp(
  { ...creationFlags, appArgs: [`int:${assetId}`] }, {}, approvalProgram, clearProgram);

// opt in to apps
runtime.optInToApp(alice.address, applicationId, {}, {});
runtime.optInToApp(bob.address, applicationId, {}, {});
```
It works fine till here. Could you please clarify regarding how do i construct the asset_transfer tx? Thanks.

PS: I notice there is a bug in `Concat(..)` operator, will add a fix.

**Comment by moon-gazer** [comment]
@ratik21 
Thanks, we also noticed a bug in concat before. Apologies for the confusion, I had to strip down a lot of code to make this example which might have lead to this confusion.

We simply want to call on_test in such a manner that it invokes the logic, it needs to changed to be something like:

`    [Txn.application_args[0] == Bytes("tt"), on_test]  `

and then one can execute a group TX.
```
[
{
    type: types.TransactionType.CallNoOpSSC,
    sign: types.SignType.SecretKey,
    fromAccountAddr: fromAccount,
    appId: applicationId,
    appArgs: ['str:tt'],
    payFlags: { totalFee: systemFee }
  }
{
    type: types.TransactionType.TransferAsset,
    sign: types.SignType.SecretKey,
    fromAccountAddr: fromAccount ,
    toAccountAddr: toAccount,
    amount: amount,
    assetID: assetID,
    payFlags: { totalFee: systemFee }
}
]
```

The smart contract line can be changed to:

`on_test = App.globalGet(Concat(Itob(Gtx[1].xfer_asset()), Bytes("test_")))
`

Doing the above will throw the error we mentioned.

**Comment by ratik21** [comment]
@moon-gazer thanks for the clarification. I tried running the transaction group you shared, but it didn't trigger any error during execution. 
I am sharing the contract & how i constructed the test. Please let me know if i did anything wrong, thanks.

*approvalProgram*
```py
from pyteal import *

def approval_program():

    on_create = Seq([
        App.globalPut(Concat(Bytes("test_"), Txn.application_args[0]), Btoi(Txn.application_args[0])),
        Int(1),
    ])

    on_closeout = Int(1)

    on_opt_in = Int(1)

    on_test = App.globalGet(Concat(Bytes("test_"), Itob(Gtxn[1].xfer_asset())))

    program = Cond(
        [Txn.application_id() == Int(0), on_create],
        [Txn.on_completion() == OnComplete.CloseOut, on_closeout],
        [Txn.on_completion() == OnComplete.OptIn, on_opt_in],
        [Txn.application_args[0] == Bytes("tt"), on_test],
    )
    return program

if __name__ == "__main__":

    print(compileTeal(approval_program(), Mode.Application))
``` 

*test.ts*
```ts
it('test group tx', () => {
  const approvalProgram = getProgram('test.py');
  const clearProgram = getProgram('clear.teal');

  const master = new AccountStore(1000e6);
  const alice = new AccountStore(minBalance, { addr: aliceAddr, sk: new Uint8Array(0) });
  const bob = new AccountStore(minBalance, { addr: bobAddr, sk: new Uint8Array(0) });
  const runtime = new Runtime([master, alice, bob]);

  creationFlags = {
    sender: alice.account,
    localInts: 1,
    localBytes: 0,
    globalInts: 2,
    globalBytes: 1
  };
  
  // deploy asset
  assetId = runtime.addAsset('gold', { creator: { ...alice.account, name: 'alice' } });

  // deploy app
  applicationId = runtime.addApp(
    { ...creationFlags, appArgs: [`int:${assetId}`] }, {}, approvalProgram, clearProgram);

  // optin to asa by receiver
  runtime.optIntoASA(assetId, bob.address, {});

  const txParams: ExecParams[] = [
    {
      type: types.TransactionType.CallNoOpSSC,
      sign: types.SignType.SecretKey,
      fromAccount: alice.account,
      appId: applicationId,
      appArgs: ['str:tt'],
      payFlags: { totalFee: 1000 }
    },
    {
      type: types.TransactionType.TransferAsset,
      sign: types.SignType.SecretKey,
      fromAccount: alice.account,
      toAccountAddr: bob.address,
      amount: 10,
      assetID: assetId,
      payFlags: { totalFee: 1000 }
    }
  ];

  runtime.executeTx(txParams); // this executed successfully, transferring 10 assets from alice to bob
})
```
NOTE: we fixed the order in `Concat(..)` Op, so i updated the order in the contract as well.

**Comment by moon-gazer** [comment]
Your execParams needs a modification.
`      appArgs: ['str:tt', `int:${assetId}`],
`

**Comment by ratik21** [comment]
> Your execParams needs a modification.
> 
> ```
> appArgs: ['str:tt',`int:${assetId}`],
> ```
Sorry, i don't seem to follow. Why do we pass `assetId` in appArgs for transfer asset? In the smart contract code (in the `on_test` branch), we don't use `Txn.applicationArgs[1]`. 
```py
 on_test = App.globalGet(Concat(Bytes("test_"), Itob(Gtxn[1].xfer_asset())))
```

> Also it should be
> App.globalPut(Concat(Bytes("test_"), Txn.application_args[1]), Btoi(Txn.application_args[1]))
In the contract shared above, we do globalPut during app creation (at `on_create` branch), so what's `application_args[0]` here? 

I can't seem to replicate your issue, as per your comments there are too many unknowns. Could you please have a look at the asc code you shared? You can just edit the smart contract code in the [comment](https://github.com/scale-it/algo-builder/issues/308#issuecomment-834728502) i added above, thanks.

**Comment by robert-zaremba** [comment]
@moon-gazer  could you check if the above solves your problem?

**Comment by moon-gazer** [comment]
Apologies for the late reply & not answering your question @ratik21. Thanks a lot @ratik21 and @robert-zaremba for the help offered. 

Will be closing the issue now, if there is any issue, other members of the team will reach out to you (after figuring out the ideal way to communicate the problem - if there is one..still attempting to figure out the root cause of our issue and whether it stems from algo-builder).
