### ISSUE TITLE
Stack Trace for Debugging

### ISSUE THREAD

**Issue by gidonkatten** [scale-it/algo-builder#356]
As discussed on the discord channel, it would be very useful if there was an option to output the stack after the execution of each opcode.

Currently if I have a failing test I have to try and isolate the problem by modifying the PyTeal or go through the long process of setting up the execution environment and using the teal debugger tool.

**Comment by ratik21** [comment]
@gidonkatten as discussed on discord, we have planned to add a helper function in our current sprint. Thanks for creating the issue :)
