### ISSUE TITLE
Problem w/ 'make sandbox-up' on mac OS 11.4 from algo-builder repository 

### ISSUE THREAD

**Issue by BubsLB** [scale-it/algo-builder#368]
Hello, i'm using Mac OS 11.4 (with docker) and I'm trying to `make sandbox-up` from algo-builder/infrastructure but it doesn't work. (Attached the log report below); while using `git clone https://github.com/algorand/sandbox.git
cd sandbox
./sandbox up` works properly.
Any suggestions ?

<img width="2048" alt="Schermata 2021-06-07 alle 11 28 49" src="https://user-images.githubusercontent.com/74781915/120997441-7c9b5880-c787-11eb-8d64-64452aca8c42.png">

**Comment by ratik21** [comment]
@BubsLB thanks for reporting. In our sandbox config `docker-compose.yml` file was out of date, updating. 
Note: before running `sandbox`, make sure ports `4001`, `4002` are idle (you can check using `lsof -i :<port>`)

**Comment by BubsLB** [comment]
> @BubsLB thanks for reporting. In our sandbox config `docker-compose.yml` file was out of date, updating.
> Note: before running `sandbox`, make sure ports `4001`, `4002` are idle (you can check using `lsof -i :<port>`)

Thanks for your answer.
But I still have the same error. Any clues ?
<img width="1280" alt="Schermata 2021-06-09 alle 16 38 48" src="https://user-images.githubusercontent.com/74781915/121375777-46a1d400-c941-11eb-8aca-5cee77a8db87.png">

**Comment by ratik21** [comment]
> But I still have the same error. Any clues ?

If you're testing code from master, it won't work as the [PR](https://github.com/scale-it/algo-builder/pull/370) is still open & isn't merged yet.
Feel free to test from the branch of PR [https://github.com/scale-it/algo-builder/tree/fix-sandbox-up](https://github.com/scale-it/algo-builder/tree/fix-sandbox-up) (either fork or checkout)
