### ISSUE TITLE
TransactionType.DeploySSC does not add app to store

### ISSUE THREAD

**Issue by pgege** [scale-it/algo-builder#371]
Hi, I have been trying to run test cases that involve Atomic Transfers. However, when I try to add an application using **TransactionType.DeploySSC** it executes but the app is not added/deployed to the store. 
```
<ref *1> Runtime {
  store: {
    accounts: Map(1) {
      '6JHI7HVPHRALW3JO5NMFAKUNJVLLV7NTNC3D645MLYNJ7EJWVDVRCUIQO4' => [AccountStore]
    },
    globalApps: Map(0) {},
    assetDefs: Map(0) {}
  },
```
 When I try to add the same Stateful Smart Contract using the **runtime.addApp** function, it works properly resulting in this:
```
<ref *1> Runtime {
  store: {
    accounts: Map(1) {
      'XDKZ6KLRFR7WD4LAKAAKZ6FUOOUHEFOZ6SANFQ2CHTE4HI437HLQRPTX3Q' => [AccountStore]
    },
    globalApps: Map(1) {
      1 => 'XDKZ6KLRFR7WD4LAKAAKZ6FUOOUHEFOZ6SANFQ2CHTE4HI437HLQRPTX3Q'
    },
    assetDefs: Map(0) {}
  },
```
This is the code I have written in order to deploy an app, I'm quite sure it's correct but I may be wrong once again:
```
runtime.executeTx(
  {
    type: types.TransactionType.DeploySSC,
    sign: types.SignType.SecretKey,
    fromAccount: master.account,
    approvalProgram: approvalProgram,
    globalBytes: 5,
    globalInts: 4,
    localBytes: 0,
    localInts: 0,
    appArgs: [
      "int:0",
      "int:25412621"
    ],
    payFlags: { totalFee: 1000 }
  }
)
```

**Comment by amityadav0** [comment]
Hi, i tried deploying using 
```
runtime.executeTx({
      type: TransactionType.DeploySSC,
      sign: SignType.SecretKey,
      fromAccount: john.account,
      approvalProgram: approvalProgram,
      clearProgram: clearProgram,
      globalBytes: 5,
      globalInts: 4,
      localBytes: 0,
      localInts: 0,
      appArgs: [
        "int:0",
        "int:25412621"
      ],
      payFlags: { totalFee: 1000 }
    });
```
![asdf](https://user-images.githubusercontent.com/26249903/121396377-f2164d00-c970-11eb-86ec-1c69a6461009.png)

you can also refer to https://github.com/scale-it/algo-builder/blob/f45382d3fab32edad856d6bd952b6703950075c8/packages/runtime/test/integration/execute-transaction.ts#L156

i think probably this is happening because clearProgram is not passed.
are you using this in js project ? using ts project is really helpful, it shows type error instantly.

also, we will be adding more docs about parameters.

Please let me know if this solves your problem

**Comment by pgege** [comment]
I'm still facing the same problem, I went ahead to try out the example from the reference as well and it still wasn't deployed. I'm using the yarn installed version of algob by the way.

**Comment by amityadav0** [comment]
okay, version maybe the problem, you can use `yarn link` to link with the latest code,
```
git clone https://github.com/scale-it/algo-builder.git
cd algo-builder
yarn install
yarn build
cd packages/algob
yarn link
```

**Comment by pgege** [comment]
Hi, Thanks I was able to deploy the app once I used the latest code. However I've run into another problem. When I attempt to call the deployed application i get the following error:
```
RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to access memory outside buffer bounds
      at boundsError (internal/buffer.js:81:11)
      at Buffer.readBigUInt64BE (internal/buffer.js:114:5)
      at Btoi.execute (/home/paul/Desktop/algo_proj/algo-builder/packages/runtime/build/interpreter/opcode-list.js:882:43)
      at Interpreter.execute (/home/paul/Desktop/algo_proj/algo-builder/packages/runtime/build/interpreter/interpreter.js:147:25)
      at Runtime.run (/home/paul/Desktop/algo_proj/algo-builder/packages/runtime/build/runtime.js:496:21)
      at /home/paul/Desktop/algo_proj/algo-builder/packages/runtime/build/ctx.js:387:34
      at Array.forEach (<anonymous>)
      at Ctx.processTransactions (/home/paul/Desktop/algo_proj/algo-builder/packages/runtime/build/ctx.js:366:19)
      at Runtime.executeTx (/home/paul/Desktop/algo_proj/algo-builder/packages/runtime/build/runtime.js:482:18)
      at Context.<anonymous> (test/sample-test.js:186:13)
      at processImmediate (internal/timers.js:462:21)
```

Here is the transaction I have attempted to execute  **contracEntryTx** is the transaction:
```
    const createContractTxGroup = [
      {
        type: types.TransactionType.DeploySSC,
        sign: types.SignType.SecretKey,
        fromAccount: contract_owner.account,
        approvalProgram: approvalProgram,
        clearProgram: clearProgram,
        localInts: 0,
        localBytes: 0,
        globalInts: 4,
        globalBytes: 5,
        appArgs: [
          "int:0",
          "int:25412621"
        ],
        payFlags: { totalFee: validTxFee }
      },
      {
        type: types.TransactionType.TransferAlgo,
        sign: types.SignType.SecretKey,
        fromAccount: contract_owner.account,
        toAccountAddr: escrow.address,
        amountMicroAlgos: contractFunds,
        payFlags: { totalFee: validTxFee }
      }
    ];

    runtime.executeTx(createContractTxGroup);

    syncAccounts();

    const iterator = runtime.store.globalApps.keys();
    const appId = iterator.next().value;

    const appArgs = [stringToBytes('submit'), stringToBytes('50')]

    const appAccounts = [
      developer.address,
      escrow.address
    ]

    const contractEntryTx = {
      type: types.TransactionType.CallNoOpSSC,
      sign: types.SignType.SecretKey,
      fromAccount: contract_owner.account,
      appId,
      payFlags: {totalFee: validTxFee},
      appArgs,
      accounts: appAccounts
    }

    runtime.executeTx(contractEntryTx);
```

Here's a snippet of the code for the stateful smart contract being deployed (I have included the code that is executed on submission to the contract.
```

    ESCROW_ACCOUNT = 2
    DEVELOPER_ACCOUNT = 1

    # ensuring the account is funded with minimum amount of funds specified before allowing submissions
    is_account_funded = Balance(Int(ESCROW_ACCOUNT)) >= Int(withdraw_amount)
    
    on_submit = Seq([
        Assert(
            is_creator
        ),
        Assert(
            Global.round() >= Btoi(App.globalGet(Bytes("SubmissionBegin")))
        ),
        Assert(
            Global.round() <= Btoi(App.globalGet(Bytes("SubmissionEnd")))
        ),
        If(Btoi(Txn.application_args[1]) > Btoi(App.globalGet(Bytes("LeaderScore"))), 
            Return(Int(0))
        ),
        App.globalPut(Bytes("LeaderAddress"), Txn.accounts[DEVELOPER_ACCOUNT]),
        App.globalPut(Bytes("LeaderScore"), Txn.application_args[1]),
        Return(is_account_funded)
    ])
``` 

If you can assist with this that would be great. Thanks!

**Comment by amityadav0** [comment]
Hi
```
Assert(
            Global.round() >= Btoi(App.globalGet(Bytes("SubmissionBegin")))
        ),
        Assert(
            Global.round() <= Btoi(App.globalGet(Bytes("SubmissionEnd")))
        ),
```
i need some more detail about this, are these values stored as Bytes while creating application ?
or as integers as in this case
`App.globalPut(Bytes("SubmissionEnd"), Btoi(Txn.application_args[1]))`

**Comment by amityadav0** [comment]
oh, got it, error is coming from here `stringToBytes('50')` you need to convert from integer to bytes instead of string.

also, we have added debug trace, you can check the values being pushed into stack at each step. it is very useful for debugging
https://github.com/scale-it/algo-builder/blob/master/docs/guide/testing-teal.md#debugging

**Comment by pgege** [comment]
This is an example goal command which is why I used the `stringToBytes('50')`.
```
./goal app call --app-id 1 --from [contract_owner_address] --app-arg "str:submit" --app-arg "str:50" --app-account [developer_address] --app-account [escrow_address]
```
I have tried the following as well but still get the same error: `parseSSCAppArgs(['str:submit','str:50'])`

**Comment by pgege** [comment]
The smart contract/app essentially takes the number passed along with `'str:50'` and compares it with the current score. If the passed argument value, `50` in this case is less than the currently stored score. Then the newly passed argument/value is stored along with the address passed with the call to the app.

**Comment by amityadav0** [comment]
okay, it think we should pass it as `int:50`. because we are converting a integer into bytes and then back to integer from bytes.

**Comment by amityadav0** [comment]
let me check if passing `str:50` works on algorand node, probably it will give some other value or throw error.

**Comment by pgege** [comment]
This is how the value is stored in the global state on my algorand node.
```
"LeaderScore": {
    "tb": "25",
    "tt": 1
  },
```
`str:50` works as an `app-arg` on my algorand node.

**Comment by amityadav0** [comment]
Okay, thanks. looking into it

**Comment by robert-zaremba** [comment]
We suspect that there is some rubbish number trying to convert to integer. Let's by creating TEAL code with 2 branches:

1. Set the value using `str:50` to `"mynumber"` global.
2. Read the value using `Btoi(...)` and compare it to a hardcoded integer in TEAL:
    ```
    Assert(
        Int(50) == Btoi(App.globalGet(Bytes("mynumber")))
    )
    ```

And run it in both our runtime and the go-algorand node.

**Comment by amityadav0** [comment]
Hi
Checked on algorand node, Btoi("str:50") indeed gives some garbage value, which greater than Int(50) that's why the code passes, 
- only fails if you compare exact values (`==`) instead of (`>`).

https://github.com/scale-it/algo-builder/tree/test-example/examples/check

![equal](https://user-images.githubusercontent.com/26249903/121863514-91449700-cd19-11eb-9f78-455a38b5e1ce.png)

**Comment by robert-zaremba** [comment]
Algo Builder helped to detect nasty bug / misuse :+1:

**Comment by pgege** [comment]
Thanks a lot guys! It works now. 

I have one final step in my test suite which is to test withdrawing the funds. Here is my code:
```
// setup escrow account
    const escrowProg = getProgram('escrow_contract.py');
    const lsig = runtime.getLogicSig(escrowProg, []);
    const escrowAddress = lsig.address();

    // sync escrow account
    escrow = runtime.getAccount(escrowAddress);
    console.log('Escrow Address: ', escrowAddress);

    // create application
    const createContractTxGroup = [
      {
        type: types.TransactionType.DeploySSC,
        sign: types.SignType.SecretKey,
        fromAccount: contract_owner.account,
        approvalProgram: approvalProgram,
        clearProgram: clearProgram,
        localInts: 0,
        localBytes: 0,
        globalInts: 4,
        globalBytes: 5,
        appArgs: [
          "int:0",
          "int:25412621"
        ],
        payFlags: { totalFee: validTxFee }
      },
      {
        type: types.TransactionType.TransferAlgo,
        sign: types.SignType.SecretKey,
        fromAccount: contract_owner.account,
        toAccountAddr: escrowAddress,
        amountMicroAlgos: contractFunds,
        payFlags: { totalFee: validTxFee }
      }
    ];

    runtime.executeTx(createContractTxGroup);

    syncAccounts();

    const iterator = runtime.store.globalApps.keys();
    const appId = iterator.next().value;

    const appAccounts = [
      developer.address,
      escrow.address
    ]

    const contractEntryTx = {
      type: types.TransactionType.CallNoOpSSC,
      sign: types.SignType.SecretKey,
      fromAccount: contract_owner.account,
      appId,
      payFlags: {totalFee: validTxFee},
      appArgs: ['str:submit','int:50'],
      accounts: appAccounts
    }

    runtime.executeTx(contractEntryTx);
    
    syncAccounts();

    appArgs = [stringToBytes('deposit')];
    txGroup = [
      {
        type: types.TransactionType.CallNoOpSSC,
        sign: types.SignType.SecretKey,
        fromAccount: developer.account,
        appId,
        payFlags: { totalFee: 1000 },
        appArgs: appArgs
      },
      {
        type: types.TransactionType.TransferAlgo,
        sign: types.SignType.LogicSignature,
        fromAccountAddr: escrow.account.addr,
        toAccountAddr: developer.address,
        amountMicroAlgos: 0,
        lsig: lsig,
        payFlags: { totalFee: 1000, closeRemainderTo: developer.address }
      }
    ];
    
    runtime.executeTx(txGroup);
```

When I execute the last transaction (`txGroup`) to withdraw, I get the following error:
```
Error: RUNTIME_ERR1401: Cannot withdraw 1000 microalgos from account EO7DEARIDKG2C4LXX2KI2UGACPGAKDW5SK5EJJQ24HCCYT3BASEWUHJZHI: resulting balance would be insufficient
```

I used the crowdfunding example as a reference, I would expect the `closeRemainderTo` to prevent this from happening. Is there something I'm doing wrong?

**Comment by amityadav0** [comment]
Hi
this error occurs when resulting account balance after transaction is less than min Balance, minimum balance increases when account is opted-in(to ASA or SSC) or created asa or ssc, 
Possible cases:
1. does developer.account has enough balance to cover fees ?
2. does escrow account has enough balance ?

when we use closeRemainderTo, it ensures, all the remaining balance is sent to closeRemainderTo address after transaction is completed, in this case i think transaction is failing before

**Comment by pgege** [comment]
The error occurs for the escrow account, I noticed something odd when I printed out the balances in the accounts.
```
Stateful smart contract withdrawal
developer account 50000000n
developer address SFTRLDTYSEOMVWVQNQFCMEHVOMKEZYYGP6EIJIFENDSQYXUGXLMT7QG7L4
escrow account 202000n
escrow address 44BF7PCMOGR2CEQTQYDWIXHTPSGMLBZODM5A66HCSV25ZQKBPNVJY2HULY
    1) should allow withdrawal for winner


  4 passing (547ms)
  1 failing

  1) Stateful smart contract withdrawal
       should allow withdrawal for winner:
     Error: RUNTIME_ERR1401: Cannot withdraw 272000 microalgos from account 44BF7PCMOGR2CEQTQYDWIXHTPSGMLBZODM5A66HCSV25ZQKBPNVJY2HULY: resulting balance would be insufficient
      at Ctx.assertMinBalance (/home/paul/Desktop/algo_proj/algo-builder/packages/runtime/build/ctx.js:24:19)
      at Ctx.deductFee (/home/paul/Desktop/algo_proj/algo-builder/packages/runtime/build/ctx.js:219:14)
      at /home/paul/Desktop/algo_proj/algo-builder/packages/runtime/build/ctx.js:368:18
      at Array.forEach (<anonymous>)
      at Ctx.processTransactions (/home/paul/Desktop/algo_proj/algo-builder/packages/runtime/build/ctx.js:366:19)
      at Runtime.executeTx (/home/paul/Desktop/algo_proj/algo-builder/packages/runtime/build/runtime.js:482:18)
      at Context.<anonymous> (test/sample-test.js:401:13)
      at processImmediate (internal/timers.js:462:21)
```

The error shows that 272000 is being withdrawn. However, it's a closeout command so the value truly should be 202000. I have checked the amount transferred to the escrow as well and it's 202000. I'm not sure where the extra 70000 being withdrawn comes from. Once again here is the transaction I am attempting to execute:
```
const withdrawFundsTxGroup = [
      {
        type: types.TransactionType.CallNoOpSSC,
        sign: types.SignType.SecretKey,
        fromAccount: contract_owner.account,
        appId,
        appArgs: [
          "str:deposit",
        ],
        payFlags: { totalFee: validTxFee }
      },
      {
        type: types.TransactionType.TransferAlgo,
        sign: types.SignType.LogicSignature,
        fromAccountAddr: escrow.account.addr,
        toAccountAddr: GLOBAL_ZERO_ADDRESS,
        amountMicroAlgos: 0,
        lsig: lsig,
        payFlags: {closeRemainderTo: developer.address}
      }
    ];
```

**Comment by amityadav0** [comment]
this happening probably because you have not passed `totalFee` in payFlags, by default suggested params fee could be higher, as in this case.

does this solves this ?

**Comment by amityadav0** [comment]
this is happening probably because you have not passed totalFee in payFlags, by default when transaction parameters are processed fee could be higher, as in this case.

does this solves this ?

**Comment by pgege** [comment]
When I add the totalFee in payFlags I run into this error that I pointed out earlier in this reply:

> Thanks a lot guys! It works now. I changed my contract to accept "int:50" instead.
> 
> I have one final step in my test suite which is to test withdrawing the funds. Here is my code:
> 
> ```
> // setup escrow account
>     const escrowProg = getProgram('escrow_contract.py');
>     const lsig = runtime.getLogicSig(escrowProg, []);
>     const escrowAddress = lsig.address();
> 
>     // sync escrow account
>     escrow = runtime.getAccount(escrowAddress);
>     console.log('Escrow Address: ', escrowAddress);
> 
>     // create application
>     const createContractTxGroup = [
>       {
>         type: types.TransactionType.DeploySSC,
>         sign: types.SignType.SecretKey,
>         fromAccount: contract_owner.account,
>         approvalProgram: approvalProgram,
>         clearProgram: clearProgram,
>         localInts: 0,
>         localBytes: 0,
>         globalInts: 4,
>         globalBytes: 5,
>         appArgs: [
>           "int:0",
>           "int:25412621"
>         ],
>         payFlags: { totalFee: validTxFee }
>       },
>       {
>         type: types.TransactionType.TransferAlgo,
>         sign: types.SignType.SecretKey,
>         fromAccount: contract_owner.account,
>         toAccountAddr: escrowAddress,
>         amountMicroAlgos: contractFunds,
>         payFlags: { totalFee: validTxFee }
>       }
>     ];
> 
>     runtime.executeTx(createContractTxGroup);
> 
>     syncAccounts();
> 
>     const iterator = runtime.store.globalApps.keys();
>     const appId = iterator.next().value;
> 
>     const appAccounts = [
>       developer.address,
>       escrow.address
>     ]
> 
>     const contractEntryTx = {
>       type: types.TransactionType.CallNoOpSSC,
>       sign: types.SignType.SecretKey,
>       fromAccount: contract_owner.account,
>       appId,
>       payFlags: {totalFee: validTxFee},
>       appArgs: ['str:submit','int:50'],
>       accounts: appAccounts
>     }
> 
>     runtime.executeTx(contractEntryTx);
>     
>     syncAccounts();
> 
>     appArgs = [stringToBytes('deposit')];
>     txGroup = [
>       {
>         type: types.TransactionType.CallNoOpSSC,
>         sign: types.SignType.SecretKey,
>         fromAccount: developer.account,
>         appId,
>         payFlags: { totalFee: 1000 },
>         appArgs: appArgs
>       },
>       {
>         type: types.TransactionType.TransferAlgo,
>         sign: types.SignType.LogicSignature,
>         fromAccountAddr: escrow.account.addr,
>         toAccountAddr: developer.address,
>         amountMicroAlgos: 0,
>         lsig: lsig,
>         payFlags: { totalFee: 1000, closeRemainderTo: developer.address }
>       }
>     ];
>     
>     runtime.executeTx(txGroup);
> ```
> 
> When I execute the last transaction (`txGroup`) to withdraw, I get the following error:
> 
> ```
> Error: RUNTIME_ERR1401: Cannot withdraw 1000 microalgos from account EO7DEARIDKG2C4LXX2KI2UGACPGAKDW5SK5EJJQ24HCCYT3BASEWUHJZHI: resulting balance would be insufficient
> ```
> 
> I used the crowdfunding example as a reference, I would expect the `closeRemainderTo` to prevent this from happening. Is there something I'm doing wrong?

**Comment by amityadav0** [comment]
okay, i am not able to recreate this issue, we have test for it https://github.com/scale-it/algo-builder/blob/ed8128f8908e9d28d83081806cd33d55f5b77c7d/packages/runtime/test/integration/escrow-account.ts#L117
let me try one more thing

**Comment by amityadav0** [comment]
this error probably occurs while deducting fee,  tried a test with group tx also, not able to recreate

**Comment by amityadav0** [comment]
```
The error shows that 272000 is being withdrawn. However, it's a closeout command so the value truly should be 202000. I have checked the amount transferred to the escrow as well and it's 202000. I'm not sure where the extra 70000 being withdrawn comes from. Once again here is the transaction I am attempting to execute:
```
could you check these logs after passing totalFee ?

**Comment by pgege** [comment]
I tried adding it, here is my code:
```
    const withdrawFundsTxGroup = [
      {
        type: types.TransactionType.CallNoOpSSC,
        sign: types.SignType.SecretKey,
        fromAccount: contract_owner.account,
        appId,
        appArgs: [
          "str:deposit",
        ],
        payFlags: { totalFee: validTxFee }
      },
      {
        type: types.TransactionType.TransferAlgo,
        sign: types.SignType.LogicSignature,
        fromAccountAddr: escrow.account.addr,
        toAccountAddr: GLOBAL_ZERO_ADDRESS,
        amountMicroAlgos: 0,
        lsig: lsig,
        payFlags: {totalFee:1000, closeRemainderTo: developer.address}
      }
    ];
```
However I get the following error:
```
Error: RUNTIME_ERR1401: Cannot withdraw 1000 microalgos from account YRH6HL54QZUVWJNN4TQCIMTCMTRPAM6SFBPLDMWCMQAI3SBQQICSNXLVRQ: resulting balance would be insufficient
      at Ctx.assertMinBalance (/home/paul/Desktop/algo_proj/algo-builder/packages/runtime/build/ctx.js:24:19)
      at Ctx.deductFee (/home/paul/Desktop/algo_proj/algo-builder/packages/runtime/build/ctx.js:219:14)
      at /home/paul/Desktop/algo_proj/algo-builder/packages/runtime/build/ctx.js:368:18
      at Array.forEach (<anonymous>)
      at Ctx.processTransactions (/home/paul/Desktop/algo_proj/algo-builder/packages/runtime/build/ctx.js:366:19)
      at Runtime.executeTx (/home/paul/Desktop/algo_proj/algo-builder/packages/runtime/build/runtime.js:482:18)
      at Context.<anonymous> (test/sample-test.js:401:13)
      at processImmediate (internal/timers.js:462:21)
```

**Comment by amityadav0** [comment]
in this case what is the balance of address in the error ?

**Comment by pgege** [comment]
It's the escrow account and it has 202000 as well. Here's a log of the accounts:
```
developer account 50000000n
developer address X7OG5HNSPK2777NNWXFRC2TNTIYVZYOY5VU7MDLNJYTXCZ5EGXSOR6TRC4
escrow account 202000n
escrow address YRH6HL54QZUVWJNN4TQCIMTCMTRPAM6SFBPLDMWCMQAI3SBQQICSNXLVRQ
    1) should allow withdrawal for winner


  4 passing (640ms)
  1 failing

  1) Stateful smart contract withdrawal
       should allow withdrawal for winner:
     Error: RUNTIME_ERR1401: Cannot withdraw 1000 microalgos from account YRH6HL54QZUVWJNN4TQCIMTCMTRPAM6SFBPLDMWCMQAI3SBQQICSNXLVRQ: resulting balance would be insufficient
      at Ctx.assertMinBalance (/home/paul/Desktop/algo_proj/algo-builder/packages/runtime/build/ctx.js:24:19)
      at Ctx.deductFee (/home/paul/Desktop/algo_proj/algo-builder/packages/runtime/build/ctx.js:219:14)
      at /home/paul/Desktop/algo_proj/algo-builder/packages/runtime/build/ctx.js:368:18
      at Array.forEach (<anonymous>)
      at Ctx.processTransactions (/home/paul/Desktop/algo_proj/algo-builder/packages/runtime/build/ctx.js:366:19)
      at Runtime.executeTx (/home/paul/Desktop/algo_proj/algo-builder/packages/runtime/build/runtime.js:482:18)
      at Context.<anonymous> (test/sample-test.js:401:13)
      at processImmediate (internal/timers.js:462:21)
```

**Comment by amityadav0** [comment]
okay, got it, i think you are using previous version of algob, 
this is happening because of algorand min_balance.

In previous version min balance is  = 1e6 that's why the code is failing

https://github.com/scale-it/algo-builder/commit/e93f75ff45452f1eadb5e035e97af7c2c15c82da
we have updated the min balance in this PR by taking reference from here https://github.com/algorand/go-algorand/blob/02eacd13d55251c854042a12eca8dc066d840e8c/config/consensus.go#L672 (Updated new min balance is 0.1e6)

**Comment by amityadav0** [comment]
so to fix this you will have to increase the escrow balance.

**Comment by pgege** [comment]
That fixed it! Thanks for all the help!
