### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by unfresco** [scale-it/algo-builder#372]
Great framework unmatched by it’s look! [Here you go](https://gateway.pinata.cloud/ipfs/QmZASrGLrE7zFdmn2mdc19rSPiDjyYud737cvzLvYgZR3z)! 

![](https://gateway.pinata.cloud/ipfs/QmZASrGLrE7zFdmn2mdc19rSPiDjyYud737cvzLvYgZR3z)

The ideas behind it are hopefully obvious to you guys. Feel free to use it and contact if you like also the vector files.

**Comment by robert-zaremba** [comment]
This looks great. Let me check with the team. Thanks for the proposal and work.

**Comment by robert-zaremba** [comment]
@unfresco we would like to use the proposed logo. How should we proceed? Can you contact me on Discord or telegram? https://t.me/robert_zaremba

**Comment by robert-zaremba** [comment]
Thank you for the great work  :1st_place_medal: . we already updated the website to use the new logo.
