### ISSUE TITLE
Cannot Opt Into Asset

### ISSUE THREAD

**Issue by gidonkatten** [scale-it/algo-builder#404]
## Describe the bug
You cannot opt into an asset using asset transfer transaction.

#### Expected Behavior
Should be able to opt into an asset with asset transfer transaction.

#### Current Behavior
`Error: RUNTIME_ERR1404: Account ENBABX5NX4CCBETS2MJWYFIGTXA6TVTML7FBDLNR4NIPMYEKT2VHM7JWEQ doesn't hold asset index 1`

from this line https://github.com/scale-it/algo-builder/blob/master/packages/runtime/src/ctx.ts#L277

## Possible Solution
You should catch the error thrown and check for this https://github.com/scale-it/algo-builder/blob/master/packages/runtime/src/ctx.ts#L281 and then only throw the error if you are not opting into asset.

## Steps to Reproduce
Create runtime asset transfer transaction with 0 amount and same sender and asset receiver.

**Comment by ratik21** [comment]
@gidonkatten thanks for spotting. It is a bug.

**Comment by ratik21** [comment]
fixed in `v1.1.1`
