### ISSUE TITLE
Runtime, optInAccNames problem w/ Asa definition

### ISSUE THREAD

**Issue by BubsLB** [scale-it/algo-builder#423]
## Describe the bug
In runtime, I've to opt in a couple of accounts in ASA. I do that directly in `Assets/asa.yaml` with `optInAccNames: ["alice", "bob"]`. when I run the test, an error returns to me as below.

<img width="636" alt="Schermata 2021-07-20 alle 15 31 37" src="https://user-images.githubusercontent.com/74781915/126333100-61f4f5cd-ff3c-477a-b4a9-aba8138c607b.png">
<img width="760" alt="Schermata 2021-07-20 alle 15 31 25" src="https://user-images.githubusercontent.com/74781915/126333111-f6fa1e48-4688-45a4-80f9-b269eaa60d0e.png">

## Steps to Reproduce

1. 
2. 

### Environment

- OS:  iOs 11.4
- Node.js version: 14.17
- algob version: 1.1.1

**Comment by robert-zaremba** [comment]
Do you declare `alice` account in your config?

**Comment by robert-zaremba** [comment]
NOTE: you can also leave that field empty in `asa.yaml` and set it when deploying ASA in your script or test (eg if you want to use an account which is not defined in algob.config.js). Here is an example: https://github.com/scale-it/algo-builder/blob/master/examples/asa/scripts/0-gold-asa.js#L31

**Comment by BubsLB** [comment]
> NOTE: you can also leave that field empty in `asa.yaml` and set it when deploying ASA in your script or test (eg if you want to use an account which is not defined in algob.config.js). Here is an example: https://github.com/scale-it/algo-builder/blob/master/examples/asa/scripts/0-gold-asa.js#L31

Yes thanks, I solved in this way. I opened the Issue just to report it

**Comment by amityadav0** [comment]
> > NOTE: you can also leave that field empty in `asa.yaml` and set it when deploying ASA in your script or test (eg if you want to use an account which is not defined in algob.config.js). Here is an example: https://github.com/scale-it/algo-builder/blob/master/examples/asa/scripts/0-gold-asa.js#L31
> 
> Yes thanks, I solved in this way. I opened the Issue just to report it

thanks, seems we cannot pass name while creating accounts in runtime. Adding a fix for it
