### ISSUE TITLE
In runtime the function Console.log() doesn't print anything within the "it" sections

### ISSUE THREAD

**Issue by BubsLB** [scale-it/algo-builder#425]
## Describe the bug
In runtime test the function Console.log() doesn't print anything within the "it" sections.

## Steps to Reproduce

1. 
2. 

### Environment

- OS: iOS 11.4
- Node.js version: 14.17
- algob version: 1.1.1

**Comment by amityadav0** [comment]
Hi
this is happening because of this file https://github.com/scale-it/algo-builder/blob/master/test/setup.js we have muted logs while we run tests in this workspace, you can comment this file and run your tests.

**Comment by BubsLB** [comment]
Thank you !

> Hi
> this is happening because of this file https://github.com/scale-it/algo-builder/blob/master/test/setup.js we have muted logs while we run tests in this workspace, you can comment this file and run your tests.

Thank you !
