### ISSUE TITLE
Support object type for token and string type for port in config

### ISSUE THREAD

**Issue by miker83z** [scale-it/algo-builder#468]
## Describe the bug
The config only allows [string type](https://github.com/scale-it/algo-builder/blob/f226b2b3a1503cadab025e97c35ffb98fb08f99e/packages/algob/src/internal/core/config/config-validation.ts#L119) for token and number type for port, while [AlgodClient](https://github.com/algorand/js-algorand-sdk/blob/4e13d5ca525db7c6dc9e8a385e8dbf6d53d4d498/src/client/v2/algod/algod.ts#L23) accepts also an object (i.e., AlgodTokenHeader and CustomTokenHeader) for the token and string type for port. 

## Possible Solution
In [config-validation](https://github.com/scale-it/algo-builder/blob/f226b2b3a1503cadab025e97c35ffb98fb08f99e/packages/algob/src/internal/core/config/config-validation.ts):
- Validate token for string and object
- Validate port for string and number

### Environment

- algob version: 1.2.1

**Comment by ratik21** [comment]
@miker83z thanks for reporting.
