### ISSUE TITLE
AssetCloseTo parameter 

### ISSUE THREAD

**Issue by Anish-Xfinite** [scale-it/algo-builder#469]
asset close to parameter for TransferAsset transaction

**Comment by ratik21** [comment]
hi @Anish-Xfinite in `algo-builder` we're using [`payFlags.closeRemainderTo`](https://algobuilder.dev/api/algob/interfaces/runtime.types.txparams.html#closeremainderto) parameter (for both, closing an ASA holding or emptying ALGO's from an account). 

So for "asset close to", you can simply pass `closeRemainderTo` param in AssetTransfer transaction. Please let me know if that solves your issue

**Comment by Anish-Xfinite** [comment]
thanks. @ratik21
