### ISSUE TITLE
Documentation Clarifer for Asa Example

### ISSUE THREAD

**Issue by djudjuu** [scale-it/algo-builder#470]
## Is your feature request related to a problem? Please describe.

I am just learning about LogicSignatures and was following along this [tutorial](https://algobuilder.dev/guide/algob-console.html) for the algob console using the asa-example. I found that the [README](https://github.com/scale-it/algo-builder/blob/master/examples/asa/README.md) was a bit misleading as its sentence suggested there would be one stateless contract that had ALL the listed features. Also the naming of the files was misleading, as one file suggests its related to the gold-asset (3-gold-delegated-asc.teal), where it really allows only transfering of Algos.
 
## Describe the solution you'd like

I think it would have been more helpful if the test was something like this:

this example also includes stateless smart contracts that showcase the two different modes of operation (contract & signature delegation):
- 2-gold-contract.teal(LINK): A Lsig in contract mode, (funded with an ASA & Algos), such that whoever owns the LogicSignature can withdraw limited amounts of ASA or Algo
- 3-algo-delegated-asc.teal (RENAMED):  is a lsig used in delegate mode to send limited amounts of Algo on behalf of the signer of this Lsig
- 4-gold-delegated-asc.teal:  is a lsig used in delegate mode to send limited amounts of ASA on behalf of the ASA owner
- 5-contract-asa-stateless: ...

-----

Overall, I really like the examples in this repo. Thats why I wanted to contribute to making it a tiny bit better.. Keep up the good work!

**Comment by robert-zaremba** [comment]
Thanks for the suggestion and a positive comment! We will update the example.

**Comment by robert-zaremba** [comment]
It's solved in `develop` branch. We are releasing new version this week and push the documentation update to the website.
