### ISSUE TITLE
Update to upstream PyTeal (TEAL 5)

### ISSUE THREAD

**Issue by Ungolim** [scale-it/algo-builder#479]
## Is your feature request related to a problem? Please describe.

Algob is still relying on PyTeal w/ TEAL4 support, limiting developers access to new TEAL versions. PyTeal added support for the TEAL 5 release a few weeks ago

## Describe the solution you'd like

Update algob dependencies and runtime to support upstream PyTeal

**Comment by robert-zaremba** [comment]
We completed the update for TEALv4 last week (together with tests).  It's in `develop` branch. It's going to be released this week.

**Comment by Lumene98** [comment]
is there an approximate date for TEAL v5?

**Comment by Lumene98** [comment]
> @Lumene98 most likely in 2-3 weeks (let's say 3 weeks for release). We didn't have a head start as PyTEAL (there was no official spec about TAELv5 until the release).
> 
> BTW: Algo Builder v2.0 with full support for TEALv4 was released last week.

That's nice to hear! Thanks
