### ISSUE TITLE
For returns error going through array in runtime

### ISSUE THREAD

**Issue by Lumene98** [scale-it/algo-builder#481]
## Describe the bug
A for going through an array returns an error in runtime

```
@Subroutine(TealType.none)
    def update_state():
        i = ScratchVar(TealType.uint64)

        init = i.store(Int(1))
        cond = i.load() < Txn.application_args.length()
        step = i.store(i.load() + Int(2))

        return Seq(
            [
                For(init, cond, step).Do(
                    App.globalPut(
                        Txn.application_args[i.load()],
                        Btoi(Txn.application_args[i.load() + Int(1)]),
                    ),
                ),
                Int(1),
            ]
        )
``` 
This is the code(Txn.application_args  as length of 3)

#### Expected Behavior
It should go throw the array normally

#### Current Behavior
It gives on `Txn.application_args[i.load()]` the error `pyteal.TealInputError: Invalid array index: (Load slot#256)`

### Environment

- OS: [e.g. iOS] Ubuntu
- Node.js version: 14
- algob version: Develop latest

**Comment by Lumene98** [comment]
This issue is in  the `develop` branch

**Comment by amityadav0** [comment]
This seems to be pyTeal version problem, i upgraded pyteal version and this code worked.
could you please check your python and pyTeal versions ?

**Comment by Lumene98** [comment]
> This seems to be pyTeal version problem, i upgraded pyteal version and this code worked. could you please check your python and pyTeal versions ?

Yeah I realized it's giving an error on the teal version too, but I don't see why... anyway closing the issue now, thanks!

**Comment by robert-zaremba** [comment]
BTW: @Lumene98  - we provide a controlled PyTEAL virtual environment in `algo-builder` repository -- we use it in our test process. To use it, install `pipenv` and:
```
pipenv sync
pipenv shell
```

**Comment by robert-zaremba** [comment]
Here is a doc: https://algobuilder.dev/guide/README#using-pipenv
