### ISSUE TITLE
Add rekying support to runtime

### ISSUE THREAD

**Issue by robert-zaremba** [scale-it/algo-builder#512]
## Is your feature request related to a problem? Please describe.

Algo Builder test environment doesn't support account rekeying.

## Describe the solution you'd like

Update the [RuntimeAccount](https://algobuilder.dev/api/runtime/interfaces/types.RuntimeAccount.html)  type and functionality (eg by adding class methods) to support account rekeying and verification.

A complete solution will require tests.

**Comment by robert-zaremba** [comment]
Proposal:
1. add `rekey(pubkey)` method to [AccountStoreI](https://algobuilder.dev/api/runtime/interfaces/types.AccountStoreI.html#account  ) and to `[RuntimeAccount](https://algobuilder.dev/api/runtime/interfaces/types.RuntimeAccount.html)`. The former should call the latter through the account attribute.
2. In `RuntimeAccount` type we need to change `sk` to be optional and add required `pk` (pubkey) attribute. `pk` should be initialized based on `sk` when `sk` is provided.
3. `RuntimeAccount.rekey(pubkey)` should wipe sk and overwrite `pk`.
4. We need to add signature verification to the `AccountStoreI` (currently we don't check that). I think it should be added to as _else_ condition: https://github.com/scale-it/algo-builder/blob/551f3910a9060b611be63e63f9bcfe9e31a1df19/packages/runtime/src/ctx.ts#L521

**Comment by vuvth** [comment]
Thank @robert-zaremba.

**Comment by robert-zaremba** [comment]
Closed in : https://github.com/scale-it/algo-builder/pull/554

**Comment by robert-zaremba** [comment]
Closed by: #519
