### ISSUE TITLE
Bug in "Tutorial: Part 1"

### ISSUE THREAD

**Issue by tzaffi** [scale-it/algo-builder#516]
## Describe the bug
Getting the following error when running `yarn run algob deploy scripts/0-gold.js`:

```
Error ABLDR602: Error while executing script 'scripts/0-gold.js:Line:29,Position:67': Cannot read properties of undefined (reading 'addr')
```

This is because on line 21 `goldOwner = deployer.accountsByName.get('alice')` is defined but `alice` has not been defined in `algob.config.js`. (See [step 4](https://developer.algorand.org/tutorials/algorand-builder-tutorial-part1-creating-local-network-and-deploying-asa/#step-4-add-accounts-to-the-config) which omits `alice`'s account)

## Possible Solution
Provide `alice's` account information

## Steps to Reproduce

1.  Follow tutorial 1
2.  Run `yarn run algob deploy scripts/0-gold.js` as suggested in [step 5](https://developer.algorand.org/tutorials/algorand-builder-tutorial-part1-creating-local-network-and-deploying-asa/#step-5-create-a-deployment-script)

### Environment

- Node.js version:
- algob version:

**Comment by tzaffi** [comment]
@robert-zaremba ^^^

**Comment by robert-zaremba** [comment]
Thanks for reporting @tzaffi .
Unfortunately, updating tutorials is an  arduous process - we don't can't do it directly, we need to request a copy of the latest version, update it and then submit it. Usually, it takes several weeks. We will make a round of reviews.
In the meantime I suggest to use directly our examples (all tutorials are maintained as examples in our repository): https://github.com/scale-it/algo-builder/tree/master/examples
