### ISSUE TITLE
ENOENT: no such file or directory, open 'C:\...\dao\artifacts\cache\dao-app-approval.py.yaml'

### ISSUE THREAD

**Issue by IzzyCapNFT** [scale-it/algo-builder#553]
When I try to create a DAO I use the command 

```bash
yarn run algob deploy
```

The Token is created correctly and added to the master wallet. But then I recieve the next error:

```
[Error: ENOENT: no such file or directory, open 'C:\Kernel\projects\my_new_project\dao\artifacts\cache\dao-app-approval.py.yaml'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'open',
  path: 'C:\\Kernel\\projects\\my_new_project\\dao\\artifacts\\cache\\dao-app-approval.py.yaml'
}
```

And the folder dao/artifacts/cache is empty

![image](https://user-images.githubusercontent.com/92820857/150214135-6cad8bd0-1d96-4274-96dd-9d359df2e521.png)

**Comment by greyguy21** [comment]
@IzzyCapNFT hi can I ask how did you resolve this issue?
