### ISSUE TITLE
Wrong design of getGlobalState

### ISSUE THREAD

**Issue by PabloLION** [scale-it/algo-builder#590]
## Describe the bug

in [Interact with smart contracts](https://developer.algorand.org/docs/get-details/dapps/smart-contracts/frontend/apps/?from_query=global%20state#read-state) it's said :

> Read state[¶](https://developer.algorand.org/docs/get-details/dapps/smart-contracts/frontend/apps/?from_query=global%20state#read-state)
Anyone may read the [global state](https://developer.algorand.org/docs/get-details/dapps/smart-contracts/frontend/apps/#reading-global-state-from-other-smart-contracts) of any application or the [local state](https://developer.algorand.org/docs/get-details/dapps/smart-contracts/frontend/apps/#reading-local-state-from-other-accounts) of an application within a given user account using the REST API account_info endpoint.

Yet these lines can only get global state of an app created by this account, not everyone because of `getApp` queries from createdApp

https://github.com/scale-it/algo-builder/blob/a3cb569e65d3721f34f1199ba378a7a934b1d183/packages/runtime/src/account.ts#L150-L152

https://github.com/scale-it/algo-builder/blob/a3cb569e65d3721f34f1199ba378a7a934b1d183/packages/runtime/src/account.ts#L181-L182

#### Expected Behavior
`(NON_CREATOR as AccountStoreI).getGlobalState(appID, KEY)` returns same value as `(APP_CREATOR as AccountStoreI).getGlobalState(appID, KEY)`

#### Current Behavior
`(NON_CREATOR as AccountStoreI).getGlobalState(appID, KEY)` always returns undefined

## Possible Solution
I tired to PR this but I don't know how. The apps are stored under `Runtime.store`

## Steps to Reproduce

1. start a `NON_CREATOR = new AccountStore(BigInt(1e10));` and a `APP_CREATOR`.
2. create some stateful smart contract **with global state**  (KEY)
2. test`should_defined = runtime.getAccount(NON_CREATOR.address).getGlobalState(appID, KEY);`
3. the `should_defined` is undefined

### Environment

- OS: macOS 12.1
- Node.js version: v17.1.0
- algob version: 3.2.0

**Comment by robert-zaremba** [comment]
@PabloLION , you are using wrong object.
* `AccountStore` will query state registered in the account (both global for apps registered in that account and local for apps where the account opted-in)
* `Runtime.getGlobalState` will give you what you want. See the [API](https://algobuilder.dev/api/runtime/classes/Runtime.html#getGlobalState) and code: https://github.com/scale-it/algo-builder/blob/develop/packages/master/src/runtime.ts#L296

**Comment by PabloLION** [comment]
The point was that an account cannot get global state of an app not created by this account. It seems a misinterpret for me?
