### ISSUE TITLE
Cannot find module 'ts-mocha'

### ISSUE THREAD

**Issue by DedicatedDev** [scale-it/algo-builder#633]
I'm trying to run project with typescript right now. 
I've followed doc procedure. 
1. yarn add algob. 
2. yarn run init . --typescript 
project successfully created with typescript. 

after that algob test
it shows error message. 
also algob deploy. 

error meessage shows they are trying to find only javascript files. 
Is there any idea for that?

Best.

**Comment by robert-zaremba** [comment]
You need to add `ts-mocha`. Probably `yarn add -D ts-mocha` will be enough.

We will update the sample project dependencies.

**Comment by MetaB0y** [comment]
I have a similar issue, after init with `--typescript` I have the following errors when running `tsc --build .`
```
node_modules/@algo-builder/algob/build/types.d.ts:108:13 - error TS2503: Cannot find namespace 'Mocha'.

108     mocha?: Mocha.MochaOptions;
                ~~~~~

node_modules/@algo-builder/algob/build/types.d.ts:1:23 - error TS2688: Cannot find type definition file for 'mocha'.

1 /// <reference types="mocha" />
                        ~~~~~
```

Installing ts-mocha doesn't help

**Comment by vuvth** [comment]
> I have a similar issue, after init with `--typescript` I have the following errors when running `tsc --build .`
> 
> ```
> node_modules/@algo-builder/algob/build/types.d.ts:108:13 - error TS2503: Cannot find namespace 'Mocha'.
> 
> 108     mocha?: Mocha.MochaOptions;
>                 ~~~~~
> 
> node_modules/@algo-builder/algob/build/types.d.ts:1:23 - error TS2688: Cannot find type definition file for 'mocha'.
> 
> 1 /// <reference types="mocha" />
>                         ~~~~~
> ```
> 
> Installing ts-mocha doesn't help

Let follow below steps:
1. add types/mocha. Let run `yarn add @types/mocha`
2. build ts file by command `yarn tsc` (better you should yarn script for it. but it's okay if you run yarn tsc).
3. Run `yarn algob test` to test.

**Comment by vuvth** [comment]
This error was fixed on a new version of algo-builder. However it's not release yet 😢
