### ISSUE TITLE
Add support `loadLogic` for *.teal program and SCParams

### ISSUE THREAD

**Issue by huybuidac** [scale-it/algo-builder#662]
## Is your feature request related to a problem? Please describe.

I'm writing a *.teal lsig program with SCParams. But algo-builder does not support to `loadLogic` for *.teal & SCParams

https://github.com/scale-it/algo-builder/blob/master/packages/runtime/src/runtime.ts#L678
- @param scTmplParams: Smart contract template parameters (used only when compiling PyTEAL to TEAL)

## Describe the solution you'd like

- Can you support this?

## Additional context

-

**Comment by vuvth** [comment]
Thank you for your proposal! I think we shouldn't not support ScParams for teal because it make teal program unportable.

**Comment by huybuidac** [comment]
I found a workaround, but it is better if there is official support.

```js
    const pyOp = new PyCompileOp()

    let lsigProg = getProgram('lsigProg.teal')
    const [replaceParams, param] = pyOp.parseScTmplParam({
      TMPL_a: a,
      TMPL_b b,
      TMPL_c: c,
    }, true);
    lsigProg = pyOp.replaceTempValues(lsigProg, replaceParams)

    const lsigAcc = runtime.createLsigAccount(lsigProg, [])
```

**Comment by rmeena840** [comment]
@huybuidac This has been taken care of and will be available in the next release. Thanks
