### ISSUE TITLE
Contract to contract call

### ISSUE THREAD

**Issue by huybuidac** [scale-it/algo-builder#685]
## Is your feature request related to a problem? Please describe.

AVM 1.1 supports "Contract-to-Contract Calls"
https://www.algorand.com/resources/blog/hello-contract-calling

## Describe the solution you'd like

- How can I implement contract to contract call on algo-builder?

## Additional context

-

**Comment by vuvoth** [comment]
Yeah! You can test it on algo-builder develop branch. [Useful link](https://algobuilder.dev/guide/README#installation-from-master)

**Comment by vuvoth** [comment]
@huybuidac We also have plan to release new algob version. Coming soon.... 🥳
