### ISSUE TITLE
Mocha printing "ASA file not defined" 

### ISSUE THREAD

**Issue by kashishkhullar** [scale-it/algo-builder#697]
## Describe the bug

On running mocha tests, I am getting "ASA file not defined" printed on the console. This happens after I create the runtime.

_I have a stateful smart contract .teal files in the assets folder_ but **no ASA files**

#### Expected Behavior

Nothing printed when there are not ASA files in assets folder

#### Current Behavior

Printing "ASA file not defined" when there are no ASA files in the assets folder.

![image](https://user-images.githubusercontent.com/22838528/171302204-8c850251-fdad-45c6-acdb-32045231e8ce.png)

## Possible Solution

This issue possibly arises from this line called in the constructor of `Runtime`

https://github.com/scale-it/algo-builder/blob/326d6d34a7279dc0efc32cbcab0fc9ad4161c293/packages/runtime/src/runtime.ts#L77

and the warning is printed here:
https://github.com/scale-it/algo-builder/blob/326d6d34a7279dc0efc32cbcab0fc9ad4161c293/packages/runtime/src/lib/files.ts#L88

## Steps to Reproduce

1. Create a test case with before hook
2. Add `Runtime([])` call in the before hook
3. The warning will get printed in the console when you run the test using `npm test`

```js
    before(function () {
        // runs once before the first test in this block
        runtime = new Runtime([]);
    });
```
### Environment

- OS: Windows
- Node.js version: 16.15.0
- algob version: NA

**Comment by vuvoth** [comment]
Thank you for create the issue! We will fix it soon.
It's just warning so you can run test without worry about this message.

**Comment by vuvoth** [comment]
We was update algo-builder to better error/warning for deployASA in #715. Thank you!
