### ISSUE TITLE
Rename optIntoASA to optInToASA

### ISSUE THREAD

**Issue by kashishkhullar** [scale-it/algo-builder#710]
## Describe the bug

The function names are not maintained properly. For instance `optIntoASA` has **"t"** where as `optInToApp` has **"T"**. To avoid confusion and consistency I suggest that we should only have `optIntoASA` and `optInToASA` where **"t"** is used.

## Possible Solution
Rename all references of `optIntoASA` -> `optInToASA`

**Comment by vuvoth** [comment]
Thanks @kashishkhullar!
