### ISSUE TITLE
Allow `getProgram` to compile files outside of assets directory

### ISSUE THREAD

**Issue by MacroChip** [scale-it/algo-builder#723]
## Is your feature request related to a problem? Please describe.

I'd like to be able to use getProgram in one project to compile another project's pyteal

## Describe the solution you'd like

A few options. Could search both assets folder and the given path. Or a flag that explicitly says that filename is a path instead of assuming it's a file in assets.

**Comment by robert-zaremba** [comment]
Could you share some motivation? Why do you think it's useful? 
We want to enforce a project structure, and have projects self contained. Maybe as a workaround you can do a symbolic link?

**Comment by MacroChip** [comment]
I have a project with multiple modules. One module loads pyteal from another module. Symlinks are fine for this but of course require setting up properly.

Another use case is that I have a project that builds pyteal from any arbitrary project.

I was hoping that my proposed solutions could target the opinionated project structure while also allowing other files to load.

**Comment by robert-zaremba** [comment]
OK, we can add it.

**Comment by robert-zaremba** [comment]
Already done in the `develop` version.
