### ISSUE TITLE
 RUNTIME_ERR1003: Type of data is incorrect. Expected unsigned integer (upto 64 bit) but got 0

### ISSUE THREAD

**Issue by darmawan01** [scale-it/algo-builder#754]
## Describe the bug

Getting error when trying to deploy the Smart Contract.

`RuntimeError: RUNTIME_ERR1003: Type of data is incorrect. Expected unsigned integer (upto 64 bit) but got 0 at line 1156`

the line mentioned in error `1156` just initialize int 0, there is no action

```json
{
 errorDescriptor: {
    number: 1003,
    message: 'Type of data is incorrect. Expected %expected% but got %actual% at line %line%',
    title: 'Invalid type at line %line%',
    description: 'Error encountered while executing teal code. Type of data is\n' +
      'incorrect. Expected %expected% but got %actual% at line %line%'
  },
  number: 1003,
  args: {
    expected: 'unsigned integer (upto 64 bit)',
    actual: '0\t\t\t\t',
    line: 1156
  },
  _isRuntimeError: true
}
```

### Environment

- OS: Mac OS
- Node.js version: v16.13.1
- algob version: "@algo-builder/algob": "^5.0.1",

Maybe anyone has the same problem, or can help to solve this, thanks

**Comment by vuvoth** [comment]
Hi @darmawan01! Could you provide more details about smart contract?

**Comment by darmawan01** [comment]
you mean the line that error mentioned ?

![image](https://user-images.githubusercontent.com/23370707/182113720-6c35ae17-8c24-426e-a45a-66be137ccbeb.png)

**Comment by vuvoth** [comment]
> you mean the line that error mentioned?

Maybe I need full contract to debug. Could I have it?

**Comment by robert-zaremba** [comment]
@darmawan01 - could you share with us the TEAL code (or usable part of it)?

**Comment by robert-zaremba** [comment]
This is probably fixed in https://github.com/scale-it/algo-builder/pull/775

**Comment by sczembor** [comment]
@darmawan01  Hi, Could you update us what's the current status on it?

**Comment by robert-zaremba** [comment]
@darmawan01 could you check the develop version and see if you still have this error?
