### ISSUE TITLE
TEAL 7 makes runtime fail

### ISSUE THREAD

**Issue by MetaB0y** [scale-it/algo-builder#759]
I am doing `teal = compileTeal(pyteal, mode=Mode.Application, version=MAX_PROGRAM_VERSION)` in my PyTEAL, probably as many other people do.

PyTEAL recently updated `MAX_PROGRAM_VERSION` to 7. It makes Alogbuilder runtime fail with errors like: 
```
TypeError: Cannot read properties of undefined (reading 'has')
      at setInnerTxField (node_modules/.store/@algo-builder-runtime-npm-5.0.1-79534551d4/package/src/lib/itxn.ts:152:33)
      at ITxnField.execute (node_modules/.store/@algo-builder-runtime-npm-5.0.1-79534551d4/package/src/interpreter/opcode-list.ts:4191:38)
```
This particular error occurs because `uintTxtFields` doesn't have a key 7.

 I understand that TEAL 7 is not yet implemented neither in Algobuilder nor Algorand mainnet, but I think it should be run the same as TEAL 6 for now instead of throwing slightly mysterious errors.

**Comment by robert-zaremba** [comment]
we are slowly adding Teal v7 support.
Could you share your PyTeal code (or part of it)? This way we can prioritize the parts which are failing related to your code?

**Comment by robert-zaremba** [comment]
Should be solved here: https://github.com/scale-it/algo-builder/pull/787/files#diff-fb6d679ed8d29771c0ca17e37361f75ff22872dc78ff51f35e147ea868d90a6aR41

**Comment by robert-zaremba** [comment]
It's in our develop release, will be part of the next v6.0 release.
