### ISSUE TITLE
Algob deploy not working

### ISSUE THREAD

**Issue by MohaiminulEraj** [scale-it/algo-builder#799]
## Describe the bug
I was trying to deploy pyteal contract locally using algo-builder from algo-builder/examples/asa directory but I got error saying
### Error ABLDR602: Error while executing script 'scripts/0-gold-asa.js': Unexpected token p in JSON at position 4
![image](https://user-images.githubusercontent.com/26181243/193758667-a30b5139-be9e-4a60-a6ba-49b2cdd89db9.png)

Can anyone please tell how can I fix this bug. Thank you!

### Environment

- OS: Ubuntu 22.04
- Node.js version: v16.16.0
- algob version: 5.0.1

**Comment by rmeena840** [comment]
It seems like the account (MERKQOFDJAPOYGRV3F253TX7DFF2DKZ3U75V5HR633DLBCEC4PAA) is not funded. Try funding it first.

**Comment by sczembor** [comment]
@MohaiminulEraj It seems like you are spending from the `master` account. However it doesn't have enough funds.  Try to recreate a private net or run a script related to `setup-master-account`. These can be found in `infrastructure` directory.

**Comment by PabloLION** [comment]
It seems to me that it's not an issue but misused.

**Comment by rmeena840** [comment]
@MohaiminulEraj Can you please update if the given solution worked for you?

**Comment by MohaiminulEraj** [comment]
> @MohaiminulEraj It seems like you are spending from the `master` account. However it doesn't have enough funds.  Try to recreate a private net or run a script related to `setup-master-account`. These can be found in `infrastructure` directory.

Thanks it worked for me.
